package dev.typetype.server.services

import dev.typetype.server.models.SubtitleItem
import okhttp3.HttpUrl
import okhttp3.HttpUrl.Companion.toHttpUrlOrNull
import java.nio.charset.StandardCharsets
import java.security.MessageDigest

internal data class AndroidSubtitleTrack(
    val id: String,
    val languageTag: String,
    val displayLanguageName: String,
    val isAutoGenerated: Boolean,
    val sourceUrl: HttpUrl,
)

internal object AndroidSubtitleTrackFactory {
    fun create(videoId: String, items: List<SubtitleItem>): List<AndroidSubtitleTrack>? {
        val occurrences = mutableMapOf<String, Int>()
        return items.map { item ->
            val sourceUrl = item.url.toHttpUrlOrNull()
                ?.takeIf(::isYoutubeCaptionUrl)
                ?: return null
            val baseId = stableId(videoId, item, sourceUrl)
            val occurrence = occurrences.merge(baseId, 1, Int::plus) ?: 1
            AndroidSubtitleTrack(
                id = if (occurrence == 1) baseId else "$baseId-$occurrence",
                languageTag = item.languageTag,
                displayLanguageName = item.displayLanguageName,
                isAutoGenerated = item.isAutoGenerated,
                sourceUrl = sourceUrl,
            )
        }
    }

    private fun stableId(videoId: String, item: SubtitleItem, url: HttpUrl): String {
        val sourceIdentity = listOf("vssId", "lang", "kind", "tlang")
            .joinToString("&") { key -> "$key=${url.queryParameter(key).orEmpty()}" }
        val material = listOf(
            videoId,
            item.languageTag,
            item.isAutoGenerated.toString(),
            sourceIdentity,
        ).joinToString("\u0000")
        return MessageDigest.getInstance("SHA-256")
            .digest(material.toByteArray(StandardCharsets.UTF_8))
            .take(ID_BYTES)
            .joinToString("") { "%02x".format(it) }
    }

    private fun isYoutubeCaptionUrl(url: HttpUrl): Boolean =
        url.isHttps &&
            (url.host == "youtube.com" || url.host.endsWith(".youtube.com")) &&
            url.encodedPath == "/api/timedtext"

    private const val ID_BYTES = 12
}

internal sealed interface AndroidSubtitleInventoryResult {
    data class Ready(val tracks: List<AndroidSubtitleTrack>) : AndroidSubtitleInventoryResult
    data object Unavailable : AndroidSubtitleInventoryResult
}
