package dev.typetype.server.services

import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.TimeoutCancellationException
import kotlinx.coroutines.withTimeout
import okhttp3.HttpUrl.Companion.toHttpUrlOrNull
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.exceptions.ReCaptchaException
import org.schabi.newpipe.extractor.stream.SubtitlesStream

internal fun interface YouTubeSubtitleTrackResolver {
    suspend fun resolve(selection: YouTubeSubtitleSelection): YouTubeSubtitleResolution
}

internal class PipePipeYouTubeSubtitleResolver(
    private val extract: suspend (YouTubeSubtitleSelection) -> YouTubeSubtitleResolution =
        ::extractYouTubeSubtitle,
) : YouTubeSubtitleTrackResolver {
    override suspend fun resolve(selection: YouTubeSubtitleSelection): YouTubeSubtitleResolution = try {
        withTimeout(RESOLUTION_TIMEOUT_MS) {
            YoutubeSessionTokenScope.withoutCredentials {
                YoutubePlayerClientScope.withClient(YoutubePlayerClient.MWEB) {
                    extract(selection)
                }
            }
        }
    } catch (_: TimeoutCancellationException) {
        YouTubeSubtitleResolution.Unavailable
    } catch (error: CancellationException) {
        throw error
    } catch (error: Throwable) {
        if (error.hasCause<ReCaptchaException>()) {
            YouTubeSubtitleResolution.Throttled
        } else {
            YouTubeSubtitleResolution.Unavailable
        }
    }

    private inline fun <reified T : Throwable> Throwable.hasCause(): Boolean =
        generateSequence(this) { it.cause }.any { it is T }

    private companion object {
        const val RESOLUTION_TIMEOUT_MS = 30_000L
    }
}

private suspend fun extractYouTubeSubtitle(
    selection: YouTubeSubtitleSelection,
): YouTubeSubtitleResolution = runPipePipeCall {
    val url = "https://www.youtube.com/watch?v=${selection.videoId}"
    val service = NewPipe.getServiceByUrl(url)
    val extractor = service.getStreamExtractor(service.streamLHFactory.fromUrl(url))
    extractor.fetchPage()
    val track = extractor.getSubtitles(selection.format.mediaFormat)
        .firstOrNull { it.matchesYouTubeSubtitle(selection) }
        ?: return@runPipePipeCall YouTubeSubtitleResolution.NotFound
    val content = track.contentForYouTubeSubtitle(selection)
        ?: return@runPipePipeCall YouTubeSubtitleResolution.NotFound
    YouTubeSubtitleResolution.Ready(
        ResolvedYouTubeSubtitle(
            content = content,
            isUrl = track.isUrl,
            isLive = extractor.streamType.toApiStreamType().isLiveContentType(),
        ),
    )
}

internal fun SubtitlesStream.matchesYouTubeSubtitle(selection: YouTubeSubtitleSelection): Boolean {
    val url = content.toHttpUrlOrNull()
    val trackLanguage = languageTag.orEmpty()
    val sourceLanguage = url?.queryParameter("lang") ?: trackLanguage
    val requestedSource = selection.sourceLanguage ?: selection.language
    if (!sourceLanguage.equals(requestedSource, ignoreCase = true) &&
        !trackLanguage.equals(selection.language, ignoreCase = true)
    ) return false
    val auto = isAutoGenerated || url?.queryParameter("kind") == "asr" ||
        url?.queryParameter("vssId")?.startsWith("a.") == true
    if (auto != (selection.variant == YouTubeSubtitleVariant.Auto)) return false
    return selection.trackName == null || url?.queryParameter("name") == selection.trackName
}

internal fun SubtitlesStream.contentForYouTubeSubtitle(selection: YouTubeSubtitleSelection): String? {
    if (!isUrl) return content.takeIf { selection.translationLanguage == null }
    val url = content.toHttpUrlOrNull()?.takeIf { isYouTubeTimedTextUrl(it.toString()) } ?: return null
    return url.newBuilder()
        .setQueryParameter("fmt", selection.format.value)
        .apply {
            if (selection.translationLanguage == null) removeAllQueryParameters("tlang")
            else setQueryParameter("tlang", selection.translationLanguage)
        }
        .build()
        .toString()
}
