package dev.typetype.server.services

import dev.typetype.server.models.AudioStreamItem
import dev.typetype.server.models.PreviewFrameItem
import dev.typetype.server.models.StreamResponse
import dev.typetype.server.models.StreamSegmentItem
import dev.typetype.server.models.SubtitleItem
import dev.typetype.server.models.VideoStreamItem
import org.schabi.newpipe.extractor.stream.AudioStream
import org.schabi.newpipe.extractor.stream.Frameset
import org.schabi.newpipe.extractor.stream.StreamInfo
import org.schabi.newpipe.extractor.stream.StreamInfoItem
import org.schabi.newpipe.extractor.stream.StreamSegment
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import org.schabi.newpipe.extractor.stream.VideoStream

internal fun StreamInfo.toStreamResponse(): StreamResponse = StreamResponse(
    id = id,
    title = name ?: "",
    uploaderName = uploaderName ?: "",
    uploaderUrl = uploaderUrl ?: "",
    uploaderAvatarUrl = uploaderAvatarUrl ?: "",
    thumbnailUrl = thumbnailUrl ?: "",
    description = description?.content ?: "",
    duration = duration,
    viewCount = viewCount,
    likeCount = likeCount,
    dislikeCount = dislikeCount,
    uploadDate = textualUploadDate ?: "",
    uploaded = uploadDate?.offsetDateTime()?.toInstant()?.toEpochMilli() ?: -1L,
    uploaderSubscriberCount = uploaderSubscriberCount,
    uploaderVerified = isUploaderVerified,
    category = category ?: "",
    license = licence ?: "",
    visibility = privacy?.name?.lowercase() ?: "",
    tags = tags ?: emptyList(),
    streamType = streamType?.name?.lowercase() ?: "",
    isShortFormContent = isShortFormContent,
    requiresMembership = requiresMembership(),
    startPosition = startPosition,
    streamSegments = runCatching { streamSegments.map { it.toStreamSegmentItem() } }.getOrElse { emptyList() },
    hlsUrl = hlsUrl?.takeIf { it.startsWith("http") } ?: "",
    dashMpdUrl = dashMpdUrl?.takeIf { it.startsWith("http") } ?: "",
    videoStreams = videoStreams.map { it.toVideoStreamItem(false) },
    audioStreams = audioStreams.mapNotNull { runCatching { it.toAudioStreamItem() }.getOrNull() },
    videoOnlyStreams = videoOnlyStreams.map { it.toVideoStreamItem(true) },
    subtitles = subtitles.mapNotNull { runCatching { it.toSubtitleItem() }.getOrNull() },
    previewFrames = previewFrames.mapNotNull { runCatching { it.toPreviewFrameItem() }.getOrNull() },
    sponsorBlockSegments = runCatching { getSponsorBlockSegments().map { it.toSegmentItem() } }.getOrElse { emptyList() },
    relatedStreams = relatedItems.filterIsInstance<StreamInfoItem>().mapNotNull { runCatching { it.toVideoItem() }.getOrNull() },
)

internal fun VideoStream.toVideoStreamItem(isVideoOnly: Boolean): VideoStreamItem =
    VideoStreamItem(
        url = getContent() ?: "",
        mimeType = getFormat()?.getMimeType() ?: "",
        format = getFormat()?.name ?: "",
        resolution = getResolution(),
        bitrate = getBitrate().takeIf { it > 0 },
        codec = getCodec()?.takeIf { it.isNotBlank() },
        isVideoOnly = isVideoOnly,
        itag = getItag(),
        width = getWidth(),
        height = getHeight(),
        fps = getFps(),
        contentLength = getItagItem()?.getContentLength() ?: 0L,
        initStart = getInitStart().toLong(),
        initEnd = getInitEnd().toLong(),
        indexStart = getIndexStart().toLong(),
        indexEnd = getIndexEnd().toLong(),
    )

internal fun AudioStream.toAudioStreamItem(): AudioStreamItem = AudioStreamItem(
    url = getContent() ?: "",
    mimeType = getFormat()?.getMimeType() ?: "",
    format = getFormat()?.name ?: "",
    bitrate = averageBitrate.takeIf { it > 0 },
    codec = getCodec()?.takeIf { it.isNotBlank() },
    quality = getQuality(),
    itag = getItag(),
    contentLength = getItagItem()?.getContentLength() ?: 0L,
    initStart = getInitStart().toLong(),
    initEnd = getInitEnd().toLong(),
    indexStart = getIndexStart().toLong(),
    indexEnd = getIndexEnd().toLong(),
    audioTrackId = getAudioTrackId(),
    audioTrackName = getAudioTrackName(),
    audioLocale = getAudioLocale(),
)

internal fun SubtitlesStream.toSubtitleItem(): SubtitleItem = SubtitleItem(
    url = getContent() ?: "",
    mimeType = getFormat()?.getMimeType() ?: "",
    languageTag = getLanguageTag() ?: "",
    displayLanguageName = getDisplayLanguageName() ?: "",
    isAutoGenerated = isAutoGenerated,
)

internal fun Frameset.toPreviewFrameItem(): PreviewFrameItem = PreviewFrameItem(
    urls = getUrls() ?: emptyList(),
    frameWidth = getFrameWidth(),
    frameHeight = getFrameHeight(),
    totalCount = getTotalCount(),
    durationPerFrame = getDurationPerFrame(),
    framesPerPageX = getFramesPerPageX(),
    framesPerPageY = getFramesPerPageY(),
)

internal fun StreamSegment.toStreamSegmentItem(): StreamSegmentItem = StreamSegmentItem(
    title = getTitle() ?: "",
    startTimeSeconds = getStartTimeSeconds(),
    channelName = getChannelName(),
    url = getUrl(),
    previewUrl = getPreviewUrl(),
)
