services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    ports:
      - "6379:6379"
    ulimits:
      memlock: -1
    restart: unless-stopped

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: typetype
      POSTGRES_USER: typetype
      POSTGRES_PASSWORD: typetype
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  typetype-server:
    image: ghcr.io/priveetee/typetype-server:latest
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/typetype
      DATABASE_USER: typetype
      DATABASE_PASSWORD: typetype
      DRAGONFLY_URL: redis://dragonfly:6379
    depends_on:
      - postgres
      - dragonfly
    restart: unless-stopped

volumes:
  postgres_data:
