package dev.typetype.server.services

import dev.typetype.server.models.SubtitleItem
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.mockk
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.Assertions.assertArrayEquals
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class AndroidSubtitleServiceTest {
    @Test
    fun `inventory exposes all Token tracks with stable identities`() = runTest {
        val source = mockk<YouTubeSubtitleService>()
        val items = listOf(item("en", false), item("en", true), item("fr", false))
        coEvery { source.fetchSubtitleInventory(VIDEO_ID) } returns YouTubeSubtitleInventoryResult.Ready(items)
        val service = AndroidSubtitleService(source, mockk())

        val result = service.inventory(VIDEO_ID) as AndroidSubtitleInventoryResult.Ready

        assertEquals(3, result.tracks.size)
        assertEquals(3, result.tracks.map { it.id }.distinct().size)
    }

    @Test
    fun `temporary upstream failure refreshes inventory once`() = runTest {
        val source = mockk<YouTubeSubtitleService>()
        val http = mockk<AndroidSubtitleHttpClient>()
        val oldTrack = track(item("en", false, "signature=old"))
        val refreshedItem = item("en", false, "signature=new")
        val refreshedTrack = track(refreshedItem)
        coEvery { http.fetch(oldTrack.sourceUrl) } returns AndroidSubtitleUpstreamResult.TemporaryFailure
        coEvery { source.fetchSubtitleInventory(VIDEO_ID) } returns
            YouTubeSubtitleInventoryResult.Ready(listOf(refreshedItem))
        coEvery { http.fetch(refreshedTrack.sourceUrl) } returns AndroidSubtitleUpstreamResult.Ready(VTT)
        val service = AndroidSubtitleService(source, http)

        val result = service.content(VIDEO_ID, oldTrack) as AndroidSubtitleContentResult.Ready

        assertArrayEquals(VTT, result.bytes)
        coVerify(exactly = 1) { source.fetchSubtitleInventory(VIDEO_ID) }
    }

    @Test
    fun `repeated temporary failure remains typed and bounded`() = runTest {
        val source = mockk<YouTubeSubtitleService>()
        val http = mockk<AndroidSubtitleHttpClient>()
        val track = track(item("en", false))
        coEvery { http.fetch(any()) } returns AndroidSubtitleUpstreamResult.TemporaryFailure
        coEvery { source.fetchSubtitleInventory(VIDEO_ID) } returns
            YouTubeSubtitleInventoryResult.Ready(listOf(item("en", false)))
        val service = AndroidSubtitleService(source, http)

        assertEquals(AndroidSubtitleContentResult.TemporaryFailure, service.content(VIDEO_ID, track))
        coVerify(exactly = 2) { http.fetch(any()) }
        coVerify(exactly = 1) { source.fetchSubtitleInventory(VIDEO_ID) }
    }

    private fun track(item: SubtitleItem): AndroidSubtitleTrack =
        AndroidSubtitleTrackFactory.create(VIDEO_ID, listOf(item))!!.single()

    private fun item(
        language: String,
        auto: Boolean,
        extra: String = "signature=test",
    ) = SubtitleItem(
        url = "https://www.youtube.com/api/timedtext?v=$VIDEO_ID&lang=$language&kind=${if (auto) "asr" else ""}&$extra",
        mimeType = "application/ttml+xml",
        languageTag = language,
        displayLanguageName = language,
        isAutoGenerated = auto,
    )

    private companion object {
        const val VIDEO_ID = "dQw4w9WgXcQ"
        val VTT = "WEBVTT\n\n00:00.000 --> 00:01.000\nHello\n".toByteArray()
    }
}
