package dev.typetype.server.services

import dev.typetype.server.models.SubtitleItem
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotEquals
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Test

class AndroidSubtitleTrackFactoryTest {
    @Test
    fun `track identity ignores expiring upstream parameters`() {
        val first = track(url("signature=old&expire=1"), "English")
        val refreshed = track(url("signature=new&expire=2"), "Anglais")

        assertEquals(first.id, refreshed.id)
    }

    @Test
    fun `manual and generated tracks in one language remain distinct`() {
        val tracks = AndroidSubtitleTrackFactory.create(
            VIDEO_ID,
            listOf(
                item(url("vssId=.en"), auto = false),
                item(url("vssId=a.en&kind=asr"), auto = true),
            ),
        )!!

        assertEquals(2, tracks.size)
        assertNotEquals(tracks[0].id, tracks[1].id)
    }

    @Test
    fun `non YouTube caption URL rejects the inventory`() {
        val tracks = AndroidSubtitleTrackFactory.create(
            VIDEO_ID,
            listOf(item("https://example.com/subtitles.vtt", auto = false)),
        )

        assertNull(tracks)
    }

    private fun track(sourceUrl: String, displayName: String): AndroidSubtitleTrack =
        AndroidSubtitleTrackFactory.create(
            VIDEO_ID,
            listOf(item(sourceUrl, false, displayName)),
        )!!.single()

    private fun item(
        sourceUrl: String,
        auto: Boolean,
        displayName: String = "English",
    ) = SubtitleItem(
        url = sourceUrl,
        mimeType = "application/ttml+xml",
        languageTag = "en",
        displayLanguageName = displayName,
        isAutoGenerated = auto,
    )

    private fun url(extra: String): String =
        "https://www.youtube.com/api/timedtext?v=$VIDEO_ID&lang=en&$extra"

    private companion object {
        const val VIDEO_ID = "dQw4w9WgXcQ"
    }
}
