package dev.typetype.server.services

import okhttp3.HttpUrl.Companion.toHttpUrl
import kotlinx.coroutines.runBlocking
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.ServiceList
import org.schabi.newpipe.extractor.stream.SubtitlesStream

class PipePipeYouTubeSubtitleResolverTest {
    @Test
    fun `resolution uses the public mweb extraction context`() = runBlocking {
        val youtube = ServiceList.YouTube
        NewPipe.setYoutubePlayerClient(YoutubePlayerClient.WEB_SAFARI.value)
        youtube.setTokens("SID=session-cookie")
        youtube.setAdditionalTokens("session-pot")
        var observed: Triple<String, String, String>? = null
        val resolver = PipePipeYouTubeSubtitleResolver {
            observed = Triple(
                NewPipe.getYoutubePlayerClient(),
                youtube.tokens.orEmpty(),
                youtube.additionalTokens.orEmpty(),
            )
            YouTubeSubtitleResolution.NotFound
        }

        assertEquals(YouTubeSubtitleResolution.NotFound, resolver.resolve(selection(YouTubeSubtitleVariant.Manual)))
        assertEquals(Triple(YoutubePlayerClient.MWEB.value, "", ""), observed)
    }

    @Test
    fun `manual and automatic tracks remain distinct`() {
        val manual = track("https://www.youtube.com/api/timedtext?v=abcdefghijk&lang=en", false)
        val automatic = track("https://www.youtube.com/api/timedtext?v=abcdefghijk&lang=en&kind=asr", true)

        assertTrue(manual.matchesYouTubeSubtitle(selection(YouTubeSubtitleVariant.Manual)))
        assertFalse(manual.matchesYouTubeSubtitle(selection(YouTubeSubtitleVariant.Auto)))
        assertTrue(automatic.matchesYouTubeSubtitle(selection(YouTubeSubtitleVariant.Auto)))
        assertFalse(automatic.matchesYouTubeSubtitle(selection(YouTubeSubtitleVariant.Manual)))
    }

    @Test
    fun `translated selection preserves source language and requested translation`() {
        val track = track(
            "https://www.youtube.com/api/timedtext?v=abcdefghijk&lang=en&kind=asr&tlang=de",
            true,
        )
        val selection = selection(YouTubeSubtitleVariant.Auto).copy(
            language = "fr",
            sourceLanguage = "en",
            translationLanguage = "fr",
        )

        assertTrue(track.matchesYouTubeSubtitle(selection))
        val resolved = requireNotNull(track.contentForYouTubeSubtitle(selection)).toHttpUrl()
        assertEquals("en", resolved.queryParameter("lang"))
        assertEquals("fr", resolved.queryParameter("tlang"))
        assertEquals("vtt", resolved.queryParameter("fmt"))
    }

    @Test
    fun `inline subtitles cannot be translated by URL parameters`() {
        val inline = SubtitlesStream.Builder()
            .setContent("<tt></tt>", false)
            .setMediaFormat(MediaFormat.TTML)
            .setLanguageCode("en")
            .setAutoGenerated(false)
            .build()

        assertNull(
            inline.contentForYouTubeSubtitle(
                selection(YouTubeSubtitleVariant.Manual).copy(
                    format = YouTubeSubtitleFormat.Ttml,
                    translationLanguage = "fr",
                ),
            ),
        )
    }

    private fun track(url: String, automatic: Boolean) = SubtitlesStream.Builder()
        .setContent(url, true)
        .setMediaFormat(MediaFormat.VTT)
        .setLanguageCode("en")
        .setAutoGenerated(automatic)
        .build()

    private fun selection(variant: YouTubeSubtitleVariant) = YouTubeSubtitleSelection(
        videoId = "abcdefghijk",
        language = "en",
        variant = variant,
        format = YouTubeSubtitleFormat.Vtt,
    )
}
