package dev.typetype.server.routes

import dev.typetype.server.services.AndroidDashManifestResult
import dev.typetype.server.services.AndroidPlaybackSession
import dev.typetype.server.services.AndroidSubtitleTrack
import kotlinx.serialization.Serializable

@Serializable
internal data class AndroidPlaybackCreateRequest(
    val videoItag: Int? = null,
    val audioItag: Int? = null,
    val audioTrackId: String? = null,
)

@Serializable
internal data class AndroidPlaybackSeekRequest(
    val generation: Long,
    val playerTimeMs: Long,
)

@Serializable
internal data class AndroidPlaybackResponse(
    val sessionId: String,
    val videoId: String,
    val manifestUrl: String,
    val videoItag: Int,
    val audioItag: Int,
    val audioTrackId: String? = null,
    val generation: Long,
    val ready: Boolean,
    val status: String,
    val subtitles: List<AndroidSubtitleResponse>,
    val retryAfterMs: Long? = null,
)

@Serializable
internal data class AndroidSubtitleResponse(
    val id: String,
    val mimeType: String,
    val languageTag: String,
    val displayLanguageName: String,
    val isAutoGenerated: Boolean,
    val url: String,
)

internal fun AndroidPlaybackSession.toAndroidPlaybackResponse(
    manifest: AndroidDashManifestResult,
): AndroidPlaybackResponse = AndroidPlaybackResponse(
    sessionId = holder.sessionToken,
    videoId = holder.key.videoId,
    manifestUrl = "/api/android/youtube/playback/${holder.sessionToken}/manifest.mpd",
    videoItag = holder.videoFormat.itag,
    audioItag = holder.audioFormat.itag,
    audioTrackId = holder.audioFormat.audioTrackId,
    generation = holder.activeGeneration(),
    ready = manifest is AndroidDashManifestResult.Ready,
    status = if (manifest is AndroidDashManifestResult.Ready) "ready" else "preparing",
    subtitles = subtitles.map { it.toResponse(holder.sessionToken) },
    retryAfterMs = if (manifest is AndroidDashManifestResult.Ready) null else ANDROID_RETRY_AFTER_MS,
)

internal fun AndroidSubtitleTrack.toResponse(sessionId: String): AndroidSubtitleResponse =
    AndroidSubtitleResponse(
        id = id,
        mimeType = "text/vtt",
        languageTag = languageTag,
        displayLanguageName = displayLanguageName,
        isAutoGenerated = isAutoGenerated,
        url = "/api/android/youtube/playback/$sessionId/subtitles/$id.vtt",
    )

internal const val ANDROID_RETRY_AFTER_MS = 500L
