package dev.typetype.server.routes

import dev.typetype.server.services.AndroidDashManifestResult
import dev.typetype.server.services.AndroidPlaybackSession
import dev.typetype.server.services.AndroidSubtitleInventorySnapshot
import dev.typetype.server.services.AndroidSubtitleTrack
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
internal data class AndroidPlaybackCreateRequest(
    val videoItag: Int? = null,
    val audioItag: Int? = null,
    val audioTrackId: String? = null,
    val subtitleMode: AndroidSubtitleMode? = null,
)

@Serializable
internal enum class AndroidSubtitleMode {
    @SerialName("deferred")
    DEFERRED,
}

@Serializable
internal data class AndroidPlaybackSeekRequest(
    val generation: Long,
    val playerTimeMs: Long,
)

@Serializable
internal data class AndroidPlaybackResponse(
    val sessionId: String,
    val videoId: String,
    val manifestUrl: String,
    val videoItag: Int,
    val audioItag: Int,
    val audioTrackId: String? = null,
    val generation: Long,
    val ready: Boolean,
    val status: String,
    val subtitles: List<AndroidSubtitleResponse>,
    val subtitleInventory: AndroidSubtitleInventoryReference? = null,
    val retryAfterMs: Long? = null,
)

@Serializable
internal data class AndroidSubtitleResponse(
    val id: String,
    val mimeType: String,
    val languageTag: String,
    val displayLanguageName: String,
    val isAutoGenerated: Boolean,
    val url: String,
)

@Serializable
internal data class AndroidSubtitleInventoryReference(
    val status: String,
    val url: String,
    val retryAfterMs: Long? = null,
)

@Serializable
internal data class AndroidSubtitleInventoryPreparingResponse(
    val status: String = "preparing",
    val retryAfterMs: Long = ANDROID_SUBTITLE_RETRY_AFTER_MS,
)

@Serializable
internal data class AndroidSubtitleInventoryReadyResponse(
    val status: String = "ready",
    val tracks: List<AndroidSubtitleResponse>,
)

internal fun AndroidPlaybackSession.toAndroidPlaybackResponse(
    manifest: AndroidDashManifestResult,
): AndroidPlaybackResponse = AndroidPlaybackResponse(
    sessionId = holder.sessionToken,
    videoId = holder.key.videoId,
    manifestUrl = "/api/android/youtube/playback/${holder.sessionToken}/manifest.mpd",
    videoItag = holder.videoFormat.itag,
    audioItag = holder.audioFormat.itag,
    audioTrackId = holder.audioFormat.audioTrackId,
    generation = holder.activeGeneration(),
    ready = manifest is AndroidDashManifestResult.Ready,
    status = if (manifest is AndroidDashManifestResult.Ready) "ready" else "preparing",
    subtitles = subtitles.map { it.toResponse(holder.sessionToken) },
    subtitleInventory = subtitleInventoryReference(),
    retryAfterMs = if (manifest is AndroidDashManifestResult.Ready) null else ANDROID_RETRY_AFTER_MS,
)

internal fun AndroidSubtitleTrack.toResponse(sessionId: String): AndroidSubtitleResponse =
    AndroidSubtitleResponse(
        id = id,
        mimeType = "text/vtt",
        languageTag = languageTag,
        displayLanguageName = displayLanguageName,
        isAutoGenerated = isAutoGenerated,
        url = "/api/android/youtube/playback/$sessionId/subtitles/$id.vtt",
    )

private fun AndroidPlaybackSession.subtitleInventoryReference(): AndroidSubtitleInventoryReference? {
    if (!deferredSubtitles) return null
    val state = subtitleInventory.snapshot()
    return AndroidSubtitleInventoryReference(
        status = when (state) {
            AndroidSubtitleInventorySnapshot.Preparing -> "preparing"
            is AndroidSubtitleInventorySnapshot.Ready -> "ready"
            AndroidSubtitleInventorySnapshot.TemporaryFailure -> "unavailable"
        },
        url = "/api/android/youtube/playback/${holder.sessionToken}/subtitles",
        retryAfterMs = ANDROID_SUBTITLE_RETRY_AFTER_MS.takeIf {
            state is AndroidSubtitleInventorySnapshot.Preparing
        },
    )
}

internal const val ANDROID_RETRY_AFTER_MS = 500L
internal const val ANDROID_SUBTITLE_RETRY_AFTER_MS = 250L
