package dev.typetype.server

import dev.typetype.server.services.toAudioStreamItem
import dev.typetype.server.services.toPreviewFrameItem
import dev.typetype.server.services.toStreamSegmentItem
import dev.typetype.server.services.toSubtitleItem
import dev.typetype.server.services.toVideoStreamItem
import io.mockk.every
import io.mockk.mockk
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Test
import org.schabi.newpipe.extractor.stream.AudioStream
import org.schabi.newpipe.extractor.stream.Frameset
import org.schabi.newpipe.extractor.stream.StreamSegment
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import org.schabi.newpipe.extractor.stream.VideoStream

class StreamInfoMappersCoreTest {
    @Test
    fun `video and audio mappings keep safe defaults`() {
        val video = mockk<VideoStream>()
        every { video.getContent() } returns null
        every { video.getFormat() } returns null
        every { video.getResolution() } returns "1080p"
        every { video.getBitrate() } returns 0
        every { video.getCodec() } returns "avc1.640028"
        every { video.getItag() } returns 137
        every { video.getWidth() } returns 1920
        every { video.getHeight() } returns 1080
        every { video.getFps() } returns 30
        every { video.getItagItem() } returns null
        every { video.getInitStart() } returns 0
        every { video.getInitEnd() } returns 0
        every { video.getIndexStart() } returns 0
        every { video.getIndexEnd() } returns 0
        val mappedVideo = video.toVideoStreamItem(isVideoOnly = true)
        assertEquals("", mappedVideo.url)
        assertEquals("", mappedVideo.mimeType)
        assertNull(mappedVideo.bitrate)
        assertEquals("avc1.640028", mappedVideo.codec)

        val audio = mockk<AudioStream>()
        every { audio.getContent() } returns null
        every { audio.getFormat() } returns null
        every { audio.averageBitrate } returns 0
        every { audio.getCodec() } returns ""
        every { audio.getQuality() } returns null
        every { audio.getItag() } returns 140
        every { audio.getItagItem() } returns null
        every { audio.getInitStart() } returns 0
        every { audio.getInitEnd() } returns 0
        every { audio.getIndexStart() } returns 0
        every { audio.getIndexEnd() } returns 0
        every { audio.getAudioTrackId() } returns "en.0"
        every { audio.getAudioTrackName() } returns "English"
        every { audio.getAudioLocale() } returns "en"
        val mappedAudio = audio.toAudioStreamItem()
        assertEquals("", mappedAudio.url)
        assertEquals("", mappedAudio.mimeType)
        assertNull(mappedAudio.bitrate)
        assertNull(mappedAudio.codec)
        assertEquals("en", mappedAudio.audioLocale)
    }

    @Test
    fun `subtitle preview and segment mapping preserve payload`() {
        val subtitle = mockk<SubtitlesStream>()
        every { subtitle.getContent() } returns "https://example.com/sub.vtt"
        every { subtitle.getFormat() } returns null
        every { subtitle.getLanguageTag() } returns "en"
        every { subtitle.getDisplayLanguageName() } returns "English"
        every { subtitle.isAutoGenerated } returns true
        val mappedSubtitle = subtitle.toSubtitleItem()
        assertEquals("en", mappedSubtitle.languageTag)
        assertEquals("English", mappedSubtitle.displayLanguageName)

        val frameset = mockk<Frameset>()
        every { frameset.getUrls() } returns listOf("u1", "u2")
        every { frameset.getFrameWidth() } returns 160
        every { frameset.getFrameHeight() } returns 90
        every { frameset.getTotalCount() } returns 20
        every { frameset.getDurationPerFrame() } returns 5
        every { frameset.getFramesPerPageX() } returns 5
        every { frameset.getFramesPerPageY() } returns 4
        val mappedFrame = frameset.toPreviewFrameItem()
        assertEquals(20, mappedFrame.totalCount)
        assertEquals(2, mappedFrame.urls.size)

        val segment = mockk<StreamSegment>()
        every { segment.getTitle() } returns "Intro"
        every { segment.getStartTimeSeconds() } returns 15
        every { segment.getChannelName() } returns "Channel"
        every { segment.getUrl() } returns "https://example.com/chapter"
        every { segment.getPreviewUrl() } returns "https://example.com/preview.jpg"
        val mappedSegment = segment.toStreamSegmentItem()
        assertEquals("Intro", mappedSegment.title)
        assertEquals(15, mappedSegment.startTimeSeconds)
    }
}
