package dev.typetype.server

import dev.typetype.server.models.AudioStreamItem
import dev.typetype.server.models.StreamResponse
import dev.typetype.server.models.VideoItem
import dev.typetype.server.models.VideoStreamItem

fun testVideoStream(
    url: String = "https://example.googlevideo.com/videoplayback?id=1",
    codec: String? = "avc1.42c01e",
    format: String = "MPEG_4",
    resolution: String = "720p",
    bitrate: Int = 2000000,
    width: Int = 1280,
    height: Int = 720,
    indexStart: Long = 221,
    indexEnd: Long = 893,
    initStart: Long = 0,
    initEnd: Long = 220,
): VideoStreamItem = VideoStreamItem(
    url = url,
    mimeType = "video/mp4",
    format = format,
    resolution = resolution,
    bitrate = bitrate,
    codec = codec,
    isVideoOnly = true,
    itag = 137,
    width = width,
    height = height,
    fps = 30,
    contentLength = 10_000_000,
    initStart = initStart,
    initEnd = initEnd,
    indexStart = indexStart,
    indexEnd = indexEnd,
)

fun testAudioStream(
    url: String = "https://example.googlevideo.com/audioplayback?id=1",
    codec: String? = "mp4a.40.2",
    format: String = "M4A",
    bitrate: Int = 128,
    indexStart: Long = 100,
    indexEnd: Long = 500,
    initStart: Long = 0,
    initEnd: Long = 99,
): AudioStreamItem = AudioStreamItem(
    url = url,
    mimeType = "audio/mp4",
    format = format,
    bitrate = bitrate,
    codec = codec,
    quality = "medium",
    itag = 140,
    contentLength = 5_000_000,
    initStart = initStart,
    initEnd = initEnd,
    indexStart = indexStart,
    indexEnd = indexEnd,
    audioTrackId = null,
    audioTrackName = null,
    audioLocale = null,
)

fun testStreamResponse(
    videoOnlyStreams: List<VideoStreamItem> = listOf(testVideoStream()),
    audioStreams: List<AudioStreamItem> = listOf(testAudioStream()),
    duration: Long = 300,
    dashMpdUrl: String = "",
): StreamResponse = StreamResponse(
    id = "test-id",
    title = "Test Video",
    uploaderName = "Test Channel",
    uploaderUrl = "https://youtube.com/channel/test",
    uploaderAvatarUrl = "",
    thumbnailUrl = "",
    description = "",
    duration = duration,
    viewCount = 0,
    likeCount = 0,
    dislikeCount = 0,
    uploadDate = "",
    uploaded = 0,
    uploaderSubscriberCount = 0,
    uploaderVerified = false,
    category = "",
    license = "",
    visibility = "",
    tags = emptyList(),
    streamType = "video_stream",
    isShortFormContent = false,
    requiresMembership = false,
    startPosition = 0L,
    streamSegments = emptyList(),
    hlsUrl = "",
    dashMpdUrl = dashMpdUrl,
    videoStreams = emptyList(),
    audioStreams = audioStreams,
    videoOnlyStreams = videoOnlyStreams,
    subtitles = emptyList(),
    previewFrames = emptyList(),
    sponsorBlockSegments = emptyList(),
    relatedStreams = emptyList(),
)

